#!/bin/bash

FOLDER_TO_BACKUP=${1}
FTP_HOSTNAME=${2}
FTP_USERNAME=${3}
FTP_PASSWORD=${4}
FTP_DIRECTORY=${5}

VOLUME_SIZE=${VOLUME_SIZE:-10240}
TMPDIR=${TMPDIR:-/tmp/backup/tmp}


FTP_PASSWORD=${FTP_PASSWORD} duplicity incremental --tempdir $TMPDIR --no-encryption --volsize $VOLUME_SIZE ${FOLDER_TO_BACKUP} ftp://${FTP_USERNAME}@${FTP_HOSTNAME}/${FTP_DIRECTORY}
